kind: pipeline
name: default

steps:
- name: test
  image: ubuntu
  commands:
  - apt-get update -qq
  - apt-get install -y -qq telnet > /dev/null
  - (sleep 1; echo "stats"; sleep 2; echo "quit";) | telnet cache 11211 || true

services:
- name: cache
  image: memcached:alpine
  command: [ -vv ]
