kind: pipeline
name: default

steps:
- name: build
  image: ubuntu
  commands:
  - apt-get update -qq
  - apt update && sudo apt install -y apt-transport-https dirmngr
  - echo "deb https://deb.gremlin.com/ release non-free" | tee /etc/apt/sources.list.d/gremlin.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9CDB294B29A5B1E2E00C24C022E8EF3461A50EF6
  - apt update && apt install -y gremlin gremlind
  - apt-get install -y -qq telnet > /dev/null
  - (sleep 1; echo "stats"; sleep 300; echo "quitting";) | telnet cache 11211 || true
  - gremlin attack cpu

services:
- name: cache
  image: memcached:alpine
  command: [ -vv ]
